# Generated by Django 4.1 on 2023-06-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_studentapplication_join_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
